"""How a control on a screen is identified.

This is the smallest piece of the artifact and the one the whole design leans on.
If a locator stops resolving, replay stops working -- so the shape of this type is
effectively the shape of our answer to "how is replay deterministic?"

Everything here is expressed in accessibility-tree terms: a *role* (what kind of
control it is), an *accessible name* (what a screen reader would announce), and
optionally a *container* to scope the search. Deliberately absent: CSS selectors,
XPath, and pixel coordinates.

Why those are absent, in the order the reasons matter:

  1. The accessibility tree is the only vocabulary that also exists on native
     desktop applications, which the brief asks us to extend to. Roles, names and
     containment are what Windows UI Automation and macOS AX expose. A design
     built on CSS cannot cross that gap; this one can, by writing a new backend
     behind the same locator type.
  2. Names survive markup churn. A legacy app regenerated by a different version
     of the same vendor tool keeps the button reading "Search" while its class
     names and table nesting change underneath.
  3. Coordinates break on window size, font scaling and inserted rows, so they
     cannot go in a durable artifact even though a screenshot-driven model would
     naturally produce them.

The strategies are an *ordered* list, tried in sequence, because the surface we
measured has both clean and degraded controls -- see the tier notes on each class.
"""

from __future__ import annotations

from typing import Annotated, Literal, Union

from pydantic import BaseModel, Field

#: Accessibility roles we act on. Constrained rather than free-text so that an
#: artifact cannot smuggle in a role the executor has no handler for -- a bad
#: artifact should fail to load, not fail halfway through a banking action.
Role = Literal[
    "button",
    "textbox",
    "combobox",
    "link",
    "checkbox",
    "radio",
    "cell",
    "row",
    "table",
    "heading",
    "option",
    "alert",
]


class ContainerScope(BaseModel):
    """An ancestor to search inside, identified the same way as anything else."""

    role: Role
    name: str
    #: Substring match rather than exact. Legacy screens pad names with
    #: whitespace and non-breaking spaces, and a row's accessible name is the
    #: concatenation of its cells, so exact matching is unusable in practice.
    name_match: Literal["exact", "contains"] = "contains"
    #: Which matching container, when several match. See the uniqueness rule on
    #: `Locator`: leaving this unset means the artifact asserts there is only one,
    #: and replay fails loudly if that stops being true.
    index: int | None = None


class RoleNameStrategy(BaseModel):
    """Tier 1: role plus accessible name. The clean case.

    Measured example: the search screen exposes `textbox "Member Number"` and
    `button "Search"`. When an app labels its controls properly this is both the
    most readable and the most durable option, and it is what we prefer.
    """

    kind: Literal["role_name"] = "role_name"
    role: Role
    name: str
    name_match: Literal["exact", "contains"] = "exact"


class RoleInContainerStrategy(BaseModel):
    """Tier 2: role, scoped to a container that *does* have a name.

    Measured example: the sub-account form exposes a bare `textbox` with no
    accessible name at all, sitting inside `row "Nickname"`. The control is
    anonymous but its neighbourhood is not.

    This is the tier that earns the design. A CSS selector for the same element
    (`table tr:nth-child(2) input`) encodes *position*, so inserting a row above
    silently retargets it to the wrong field -- in a banking form, that means
    typing a deposit amount into a nickname box. Scoping to the row whose label
    reads "Nickname" encodes *meaning*, and meaning is what survives the edit.
    """

    kind: Literal["role_in_container"] = "role_in_container"
    role: Role
    container: ContainerScope
    #: Which match inside the container, when the container holds several of the
    #: same role. Zero-based, and intentionally scoped *within* the container so
    #: it never becomes a page-wide ordinal.
    #:
    #: `None` means the artifact asserts the match is unique and replay should
    #: fail loudly if it stops being so. Defaulting to 0 instead would silently
    #: re-introduce "just take the first", which is the exact behaviour the
    #: uniqueness rule on `Locator` exists to forbid.
    index: int | None = None


class RoleOrdinalStrategy(BaseModel):
    """Tier 3: role plus position on the screen. The last resort.

    Recorded with an explicit `justification` because an unqualified ordinal is
    the least durable thing we can write down, and an artifact that reaches for
    one should have to say why in text a human reviewer will read.
    """

    kind: Literal["role_ordinal"] = "role_ordinal"
    role: Role
    index: int
    justification: str


LocatorStrategy = Annotated[
    Union[RoleNameStrategy, RoleInContainerStrategy, RoleOrdinalStrategy],
    Field(discriminator="kind"),
]


class Locator(BaseModel):
    """A control's full address: which frame it lives in, then how to find it.

    `frame_path` is not decoration. The target app's top-level document contains
    no controls whatsoever -- only two `iframe` nodes -- so an address without a
    frame path does not identify anything. Naming the frames from the top document
    downward also generalises: a desktop backend reads the same field as a window
    or pane hierarchy, which is the same shape of problem.

    The uniqueness rule, which is a determinism decision as much as a locator one:
    **a strategy resolves only if it matches exactly one element.** Matching several
    is treated as a failure to resolve, not as an invitation to take the first.
    Silently taking the first is how automation reads the wrong row on the day a
    member opens a second savings account -- it does not error, it just returns
    somebody's other balance. Where several matches are genuinely expected, the
    artifact must say which one it means via an explicit index, so the ambiguity is
    a recorded decision rather than an accident of ordering.
    """

    frame_path: list[str] = Field(
        default_factory=list,
        description="Frame names from the top document inward; empty means top.",
    )
    strategies: list[LocatorStrategy] = Field(
        min_length=1,
        description="Tried in order; the first that resolves uniquely wins.",
    )
    #: Recorded at discovery time so a reviewer can read the artifact without
    #: opening the app, and so a failure message can say what we were looking for
    #: in human terms rather than quoting a strategy union.
    describes: str = Field(
        description="Plain-language description, e.g. 'the Member Number field'."
    )
